/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/rafal/Documents/Programming/Own_Adapter/documentation/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-61435b9b",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61435b9b").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-64eac0de",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64eac0de").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-994223e0",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-994223e0").then(next)
    },
  },
  {
    name: "v-13f0de89",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13f0de89").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-be7a43c4",
    path: "/languages/de/ESPHome/02.supportedTypes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-be7a43c4").then(next)
    },
  },
  {
    name: "v-a512c5f0",
    path: "/languages/de/ESPHome/05.stateExample.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a512c5f0").then(next)
    },
  },
  {
    name: "v-2c30fc10",
    path: "/languages/de/ESPHome/04.configExample.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c30fc10").then(next)
    },
  },
  {
    name: "v-047731e0",
    path: "/languages/de/ESPHome/03.adapterConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-047731e0").then(next)
    },
  },
  {
    name: "v-029298e0",
    path: "/languages/de/SourceAnalytix/03.initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-029298e0").then(next)
    },
  },
  {
    name: "v-07085882",
    path: "/languages/de/SourceAnalytix/02.adapterConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07085882").then(next)
    },
  },
  {
    name: "v-7d06691b",
    path: "/languages/de/SourceAnalytix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d06691b").then(next)
    },
  },
  {
    path: "/languages/de/SourceAnalytix/index.html",
    redirect: "/languages/de/SourceAnalytix/"
  },
  {
    name: "v-8cb3ab0a",
    path: "/languages/de/ESPHome/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8cb3ab0a").then(next)
    },
  },
  {
    path: "/languages/de/ESPHome/index.html",
    redirect: "/languages/de/ESPHome/"
  },
  {
    name: "v-e91477e0",
    path: "/languages/de/WLED/02.initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e91477e0").then(next)
    },
  },
  {
    name: "v-525bfd20",
    path: "/languages/de/WLED/03.firstSteps.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-525bfd20").then(next)
    },
  },
  {
    name: "v-09f3c5ce",
    path: "/languages/en/ESPHome/02.supportedTypes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09f3c5ce").then(next)
    },
  },
  {
    name: "v-3a3cd61b",
    path: "/languages/de/_Overview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a3cd61b").then(next)
    },
  },
  {
    path: "/languages/de/_Overview/index.html",
    redirect: "/languages/de/_Overview/"
  },
  {
    name: "v-fba53526",
    path: "/languages/de/WLED/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fba53526").then(next)
    },
  },
  {
    path: "/languages/de/WLED/index.html",
    redirect: "/languages/de/WLED/"
  },
  {
    name: "v-e1da9d76",
    path: "/languages/de/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e1da9d76").then(next)
    },
  },
  {
    path: "/languages/de/index.html",
    redirect: "/languages/de/"
  },
  {
    name: "v-c46017e0",
    path: "/languages/en/ESPHome/03.adapterConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c46017e0").then(next)
    },
  },
  {
    name: "v-a8fef290",
    path: "/languages/en/ESPHome/05.stateExample.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8fef290").then(next)
    },
  },
  {
    name: "v-6786ede0",
    path: "/languages/en/ESPHome/04.configExample.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6786ede0").then(next)
    },
  },
  {
    name: "v-43b2e10a",
    path: "/languages/en/ESPHome/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43b2e10a").then(next)
    },
  },
  {
    path: "/languages/en/ESPHome/index.html",
    redirect: "/languages/en/ESPHome/"
  },
  {
    name: "v-1d233a32",
    path: "/languages/en/SourceAnalytix/02.adapterConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d233a32").then(next)
    },
  },
  {
    name: "v-75ce2ee0",
    path: "/languages/en/SourceAnalytix/03.initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75ce2ee0").then(next)
    },
  },
  {
    name: "v-e683292a",
    path: "/languages/en/SourceAnalytix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e683292a").then(next)
    },
  },
  {
    path: "/languages/en/SourceAnalytix/index.html",
    redirect: "/languages/en/SourceAnalytix/"
  },
  {
    name: "v-f884b020",
    path: "/languages/en/WLED/03.initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f884b020").then(next)
    },
  },
  {
    name: "v-1f194fe0",
    path: "/languages/en/WLED/02.firstSteps.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f194fe0").then(next)
    },
  },
  {
    name: "v-4ff6c486",
    path: "/languages/en/WLED/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ff6c486").then(next)
    },
  },
  {
    path: "/languages/en/WLED/index.html",
    redirect: "/languages/en/WLED/"
  },
  {
    name: "v-d1c5ddca",
    path: "/languages/en/_Overview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1c5ddca").then(next)
    },
  },
  {
    path: "/languages/en/_Overview/index.html",
    redirect: "/languages/en/_Overview/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]