/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/rafal/Desktop/DutchmanNL.github.io/docs/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0886234b",
    path: "/Tado/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0886234b").then(next)
    },
  },
  {
    path: "/Tado/index.html",
    redirect: "/Tado/"
  },
  {
    name: "v-87f17f6a",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87f17f6a").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-ef401f7e",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef401f7e").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-181f1360",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-181f1360").then(next)
    },
  },
  {
    name: "v-d0ad1c6a",
    path: "/languages/de/SourceAnalytix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0ad1c6a").then(next)
    },
  },
  {
    path: "/languages/de/SourceAnalytix/index.html",
    redirect: "/languages/de/SourceAnalytix/"
  },
  {
    name: "v-f153a04e",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f153a04e").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-30ee7d24",
    path: "/languages/de/SourceAnalytix/firstSteps.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30ee7d24").then(next)
    },
  },
  {
    name: "v-0a9b650e",
    path: "/languages/de/SourceAnalytix/initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a9b650e").then(next)
    },
  },
  {
    name: "v-50b9a91e",
    path: "/languages/en/SourceAnalytix/firstSteps.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50b9a91e").then(next)
    },
  },
  {
    name: "v-6dd9fe95",
    path: "/languages/de/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6dd9fe95").then(next)
    },
  },
  {
    path: "/languages/de/index.html",
    redirect: "/languages/de/"
  },
  {
    name: "v-b13d17ca",
    path: "/languages/en/SourceAnalytix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b13d17ca").then(next)
    },
  },
  {
    path: "/languages/en/SourceAnalytix/index.html",
    redirect: "/languages/en/SourceAnalytix/"
  },
  {
    name: "v-ff966e84",
    path: "/languages/en/SourceAnalytix/initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff966e84").then(next)
    },
  },
  {
    name: "v-b1222af6",
    path: "/languages/nl/SourceAnalytix/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1222af6").then(next)
    },
  },
  {
    path: "/languages/nl/SourceAnalytix/index.html",
    redirect: "/languages/nl/SourceAnalytix/"
  },
  {
    name: "v-62d6c9d8",
    path: "/languages/nl/SourceAnalytix/initialisation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62d6c9d8").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]