/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Tuto VuePress / Netlify",
  "description": "DutchmanNL | Adapter Documentation",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/Tado/",
      "relativePath": "Tado/README.md",
      "key": "v-0886234b",
      "path": "/Tado/",
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-87f17f6a",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ],
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-ef401f7e",
      "path": "/guide/",
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/guide/using-vue.html",
      "relativePath": "guide/using-vue.md",
      "key": "v-181f1360",
      "path": "/guide/using-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "Wie macht man es",
      "frontmatter": {},
      "regularPath": "/languages/de/SourceAnalytix/",
      "relativePath": "languages/de/SourceAnalytix/README.md",
      "key": "v-d0ad1c6a",
      "path": "/languages/de/SourceAnalytix/",
      "lastUpdated": "13.1.2021, 14:23:07"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/test.png",
        "tagline": "Documentation for ioBroker adapters managed and Maintained by DutchmanNL",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by Rafal Drozda with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-f153a04e",
      "path": "/",
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "First Steps",
      "frontmatter": {},
      "regularPath": "/languages/de/SourceAnalytix/firstSteps.html",
      "relativePath": "languages/de/SourceAnalytix/firstSteps.md",
      "key": "v-30ee7d24",
      "path": "/languages/de/SourceAnalytix/firstSteps.html",
      "lastUpdated": "13.1.2021, 14:23:07"
    },
    {
      "title": "Wie initialisiere ich diesen adapter",
      "frontmatter": {},
      "regularPath": "/languages/de/SourceAnalytix/initialisation.html",
      "relativePath": "languages/de/SourceAnalytix/initialisation.md",
      "key": "v-0a9b650e",
      "path": "/languages/de/SourceAnalytix/initialisation.html",
      "lastUpdated": "13.1.2021, 14:23:07"
    },
    {
      "title": "First Steps",
      "frontmatter": {},
      "regularPath": "/languages/en/SourceAnalytix/firstSteps.html",
      "relativePath": "languages/en/SourceAnalytix/firstSteps.md",
      "key": "v-50b9a91e",
      "path": "/languages/en/SourceAnalytix/firstSteps.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/test.png",
        "tagline": "Eine übersicht meiner Open Source Software projekte",
        "actionText": "Quick Start →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Feature 1 Title",
            "details": "Feature 1 Description"
          },
          {
            "title": "Feature 2 Title",
            "details": "Feature 2 Description"
          },
          {
            "title": "Feature 3 Title",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by Rafal Drozda with ❤️"
      },
      "regularPath": "/languages/de/",
      "relativePath": "languages/de/index.md",
      "key": "v-6dd9fe95",
      "path": "/languages/de/",
      "lastUpdated": "13.1.2021, 14:23:07"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/languages/en/SourceAnalytix/",
      "relativePath": "languages/en/SourceAnalytix/README.md",
      "key": "v-b13d17ca",
      "path": "/languages/en/SourceAnalytix/"
    },
    {
      "title": "How to initialise this adapter",
      "frontmatter": {},
      "regularPath": "/languages/en/SourceAnalytix/initialisation.html",
      "relativePath": "languages/en/SourceAnalytix/initialisation.md",
      "key": "v-ff966e84",
      "path": "/languages/en/SourceAnalytix/initialisation.html"
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/languages/nl/SourceAnalytix/",
      "relativePath": "languages/nl/SourceAnalytix/README.md",
      "key": "v-b1222af6",
      "path": "/languages/nl/SourceAnalytix/",
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    },
    {
      "title": "Hoe initialiseer je deze adapter",
      "frontmatter": {},
      "regularPath": "/languages/nl/SourceAnalytix/initialisation.html",
      "relativePath": "languages/nl/SourceAnalytix/initialisation.md",
      "key": "v-62d6c9d8",
      "path": "/languages/nl/SourceAnalytix/initialisation.html",
      "lastUpdated": "1/13/2021, 2:23:07 PM"
    }
  ],
  "themeConfig": {
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": true,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "sidebar": [
          {
            "title": "SA",
            "path": "/languages/en/SourceAnalytix/",
            "collapsable": true,
            "children": [
              "/languages/en/SourceAnalytix/initialisation",
              "/languages/en/SourceAnalytix/firstSteps"
            ]
          }
        ],
        "nav": [
          {
            "text": "SourceAnalytix",
            "link": "/languages/en/SourceAnalytix/"
          },
          {
            "text": "Support Me",
            "link": "http://paypal.me/DutchmanNL"
          }
        ]
      },
      "/languages/de/": {
        "label": "Deutsch",
        "selectText": "Languages",
        "sidebar": [
          {
            "title": "SA",
            "path": "/languages/de/SourceAnalytix/",
            "collapsable": true,
            "children": [
              "/languages/de/SourceAnalytix/initialisation",
              "/languages/de/SourceAnalytix/firstSteps"
            ]
          },
          {
            "title": "Group 2",
            "children": [],
            "initialOpenGroupIndex": -1
          }
        ],
        "nav": [
          {
            "text": "SourceAnalytix",
            "link": "/languages/de/SourceAnalytix/"
          },
          {
            "text": "Support Me",
            "link": "http://paypal.me/DutchmanNL"
          }
        ]
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "DutchmanNL | Adapter Documentation",
      "description": "An overview of my open source software projects",
      "path": "/"
    },
    "/languages/de/": {
      "lang": "de-DE",
      "title": "DutchmanNL | Adapter Dokumentation",
      "description": "Eine übersicht meiner Open Source Software projekte",
      "path": "/languages/de/"
    }
  }
}